### ISSUE TITLE
Dependency on React on the server

### ISSUE THREAD

**Issue by justswim** [odysseyscience/react-s3-uploader#136]
When I install the package on my node / express server (to take advantage of the /s3 api call), I get warnings because of the client side dependencies:

warning "react-s3-uploader@4.2.0" has unmet peer dependency "react@*".
warning "react-s3-uploader@4.2.0" has unmet peer dependency "react-dom@*".

Is there a way to get rid of these warnings?

**Comment by seanadkinson** [comment]
I see, so your package.json doesn't serve your frontend and your backend?  Really the server piece should be busted out into a separate module, but I don't have time to do that.  In the meantime, we can probably just remove the `peerdependencies`, since it can be assumed people are depending on react when they need it.  Want to remove those dependencies in a PR?  Thanks

**Comment by seanadkinson** [comment]
Published `v4.5.0` with removing the peer dependencies on `react` and `react-dom`
