### ISSUE TITLE
How to customize the <input>?

### ISSUE THREAD

**Issue by kliu4** [odysseyscience/react-s3-uploader#151]
How to customize the input?

**Comment by arvinsim** [comment]
From the docs

> Extra props
>You can pass any extra props to <ReactS3Uploader /> and these will be passed down to the final <input />. which means that if you give the ReactS3Uploader a className or a name prop the input will have those as well.

**Comment by kliu4** [comment]
This makes sense. Thanks

**Comment by arvinsim** [comment]
Doesn't `bootstrap` use classes? Passing `bootstrap` classnames should work.

If you are talking about integration `react-bootstrap`, then that's another thing.

**Comment by seanpaulkelley** [comment]
The docs say to style the button by passing className as prop.  When I use bootstrap class:
`className="btn btn-primary"`

The view styles the area around the button.  How does one style just the button?
![screenshot from 2017-11-26 08-49-50](https://user-images.githubusercontent.com/8125357/33240626-0e161e2a-d287-11e7-925c-d587df544bff.png)

the source looks ok
`<input type="file" accept="image/*" class="btn btn-primary">
`

I am also curious how you customize the button text since this prop does not work
`value="Click Me"`

**Comment by seanadkinson** [comment]
Browsers pretty much decide and control how you render an `input` of type `file`.  You don't have much control over it.  Some browsers put the button on the left, some on the right, some say "choose file", some say other things.  To fully customize a file upload field, you'll need to use some other techniques, which are outside the scope of this library.  Best of luck!

**Comment by kliu4** [comment]
After using style, the input box after the button missing. Any help?

Thanks



​​

**Comment by kliu4** [comment]
After using style, the input box after the button missing. Any help?

Thanks
![reactsuploadercustomizeinput](https://user-images.githubusercontent.com/3431017/33339776-d6a638d4-d43f-11e7-9669-aa958fdb091e.png)

**Comment by seanpaulkelley** [comment]
I am not sure I follow you.  The label text styles the button and provides the test on it.  The <ReactS3Uploader... component creates the input
