### ISSUE TITLE
publicUrl is undefined

### ISSUE THREAD

**Issue by shamanking** [odysseyscience/react-s3-uploader#159]
Please help me!

I have component:

<ReactS3Uploader
        getSignedUrl={this.getSignedUrl}
        accept="image/*, application/pdf"
        uploadRequestHeaders={{
          'x-amz-acl': 'public-read',
        }}
        contentDisposition="auto"
        scrubFilename={(filename) => filename.replace(/[^\w\d_\-.]+/ig, '')}
      />

And it's implement success. But console.log in method:

S3Upload.prototype.onFinishS3Put = function(signResult, file) {
    return console.log('base.onFinishS3Put()', signResult.publicUrl);
};
is "Upload finished: undefined"

And this is log result (It does not have publicUrl): 

![screen shot 2017-12-28 at 7 07 20 pm](https://user-images.githubusercontent.com/5752503/34410380-748804f4-ec02-11e7-858e-4be56f67c240.png)

**Comment by shamanking** [comment]
``

**Comment by seanadkinson** [comment]
Looks like you are using a custom signing method of `this. getSignedUrl`.  You need to provide the `publicUrl` to the callback, if you want it to be available.  Otherwise how could anyone know what it is?  See docs on this function [here](https://github.com/odysseyscience/react-s3-uploader#using-custom-function-to-get-signedurl)

Please reopen if you have more info or questions.

**Comment by shamanking** [comment]
Thank you seanadkinson!

**Comment by willian** [comment]
@seanadkinson hi there. I am not using a custom signing method and I still don't see the `publicUrl`. What I want to do is to know what is the final URL in the S3 after the upload is succeeded.
