### ISSUE TITLE
How to pre-process serverside 

### ISSUE THREAD

**Issue by ronidavelman** [odysseyscience/react-s3-uploader#163]
Im trying to resize and minify server side, but there doesn't seem to be any options for this in:

```
app.use('/s3', require('react-s3-uploader/s3router')({
    bucket: "MyS3Bucket",
    region: 'us-east-1', //optional
    signatureVersion: 'v4', //optional (use for some amazon regions: frankfurt and others)
    headers: {'Access-Control-Allow-Origin': '*'}, // optional
    ACL: 'private', // this is default
    uniquePrefix: true // (4.0.2 and above) default is true, setting the attribute to false preserves the original filename in S3
}));
```

**Comment by seanadkinson** [comment]
Hi @ronidavelman, that would kind of defeat the purpose of this library.  The benefit of what we do here is that the client uploads the file directly to S3, saving your server from needing to proxy the bits.  If you want to resize/minify server side, then the client has already uploaded the file to your server, and instead of writing the changed file back to the client, you ought to just upload it to S3.  This library doesn't really support this use case very well (although you can do whatever you want in the `preprocess` hook).

I'm going to close this issue, but feel free to re-open if you need to.

**Comment by ronidavelman** [comment]
@seanadkinson I ended up using:

```
Preprocess = (file, next) => {
   new ImageCompressor(file, {
     quality: .8,
     convertSize: 1,
     success(result) {
       next(result)
     },
     error(e) {
       next(file)
     },
   });
xt) => {
   new ImageCompressor(file, {
     quality: .8,
     convertSize: 1,
     success(result) {
       next(result)
     },
     error(e) {
       next(file)
     },
   });
 }

```

Via https://www.npmjs.com/package/image-compressor

The convertSize: 1 forces all pngs to jpgs

**Comment by seanadkinson** [comment]
Cool, so you are resizing client side, nice 👍
