### ISSUE TITLE
export s3upload explicitly

### ISSUE THREAD

**Issue by mschipperheyn** [odysseyscience/react-s3-uploader#165]
Hi,

Love the library, but would be nice if you could export s3upload explicitly so it can be used elsewhere for upload actions that don't depend on a font end React component

**Comment by seanadkinson** [comment]
Yeah, that would be nice.  Notice there is a comment at the top of the `s3upload.js` file that references [this file](https://github.com/flyingsparx/NodeDirectUploader) as a starting point for my work here.  You could see if that file is available somewhere by itself.  Although I'm not sure how much has changed since I started this project.

Note as well, that you can import that file by itself using:

    import s3upload from 'react-s3-uploader/s3upload';

But of course you'll get this libraries `dependencies`, which you probably don't want.

PRs welcome if you find a useful way to do what you are looking for here.  Thanks
