### ISSUE TITLE
TransferPropsTo - ReactS3Uploader.js

### ISSUE THREAD

**Issue by yamill** [odysseyscience/react-s3-uploader#2]
TransferPropsTo doesn't work with latest version of React.

I changed the render method to:

    render: function() {

        return (
            React.DOM.input({type: 'file', onChange: this.uploadFile, onProgress: this.props.onProgress, onFinish: this.props.onFinish, onError: this.props.onError})
        );

    }

**Comment by seanadkinson** [comment]
Try this line instead, to make sure you keep all props passed in:

    return (
        React.DOM.input(Object.assign({}, this.props, {type: 'file', onChange: this.uploadFile, onProgress: this.props.onProgress, onFinish: this.props.onFinish, onError: this.props.onError}))
    );

If it works for you, and you want to create a PR, feel free.  Otherwise I'll try to get this updated soon.

**Comment by angkec** [comment]
Ok I came across this problem myself. @yamill's fix worked for me but not @seanadkinson's: the console from safari complained:

TypeError: undefined is not a function (evaluating 'Object.assign')

Hope this helpful.

**Comment by seanadkinson** [comment]
@angkec I think `Object.assign` is provided by `es5-shim` or `es5-sham`, which I believe React requires in order to support browser's that don't have it, but I could be wrong.

I can push a change that uses the `object-assign` dependency though.  I just had someone else submit a PR with this change to another repo here: https://github.com/odysseyscience/react-markdown-el/pull/1

Stay tuned for a quick update.

**Comment by seanadkinson** [comment]
Pushed `1.1.4`

**Comment by yamill** [comment]
Awesome thanks @seanadkinson
