### ISSUE TITLE
Allow Options for S3 Service Object to be Passed To S3 Router

### ISSUE THREAD

**Issue by kenny-house** [odysseyscience/react-s3-uploader#46]
For local development, there are a handful of useful tools that mock some of S3's functionality like https://github.com/jubos/fake-s3.

Typically using such tools requires providing an "endpoint" config option when the aws-sdk's S3 service object is constructed (http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property).

It would be useful to be able to pass an optional config object to the S3Router constructor that would then be passed to the aws-sdk when constructing the S3 object so that options such as endpoint could be provided.

 I wanted to get any thoughts on the name of the option, or alternative ideas. I'd be happy to submit a PR.

**Comment by Judahmeek** [comment]
@Kenny-House Are you still available for this?

**Comment by Kenny-House** [comment]
Hey @Judahmeek, it's been a while since I've been working with this library very much. 

I'd be happy to revisit this issue, but It will probably be a little while before I'll have availability to dive into it.

**Comment by techwes** [comment]
I am also interested in this since I ran into an error where the S3 Service Object that the S3 router was constructing was not picking up my credentials for some reason. Once I passed both my access keys it worked. So right now I had to implement the server side signing on my own but I would love to be able to use both parts of this library. 

Unless @kenny-house got some time he didnt expect, I will try to get a PR up for this soon.

**Comment by techwes** [comment]
I was actually about to work on this but realized I had a slightly different idea then @kenny-house  and wanted to implement something that helps us all. As I see it there are 3 options of things we could pass in via a new param:

1.  The configuration of S3 that gets passed directly to `new aws.S3`
2.  An already instantiated S3 Service Object
3.  A function that returns a new instantiated S3 Service Object

1 would work for the case @kenny-house  described but I don't think it is as useful for testing as 2 would be (since you could pass in an entire mock). However with 2 we would change from instantiating S3 for each request to only instantiating once in the main function body. 3 allows a full mock and keeping the current behavior but is unnecessary if there is no issue with instantiating S3 once.

What do you think?
