### ISSUE TITLE
Consider making a standalone version

### ISSUE THREAD

**Issue by vjustov** [odysseyscience/react-s3-uploader#88]
This component is actually heavily depending on npm and latinize, onorm and object-assign.

Because in the current project I'm not using node, I had to edit the source to fit my needs. The thing is, I believe that what is being achieved with latinize and onorm should be an opt-in behavior instead default. That is part of the be preprocess step in order to make sure the filename is correct.

What object-assign achieves can also be done using `$.extend` which is generally better supported.

Thoughts?

**Comment by seanadkinson** [comment]
Just released `v4.0.0`, which removed `unorm` and `latinize`.  Made the scrub function customizable, with a simple default.

Will leave `object-assign` alone for now, since `$.extend` assumes jquery (unless I'm missing something), which I wouldn't want to assume exists or depend on.  The library is tiny at least.

Thanks
